name: lcls-cu-acc-live
channels:
  - conda-forge
dependencies:
  - python=3.8
  - lume-epics=1.1
  - lume-model=1.0
  - pip
  - bokeh
  - pytao
  - bmad
  - pip: 
    - git+https://github.com/slaclab/lcls-live.git